// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	Chat: DurableObjectNamespace /* Chat from chat-bi-agent */;
	ASSETS: Fetcher;
}
